name: Docker Image Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY_URL_LIVE }}
          username: ${{ secrets.HARBOR_USERNAME_LIVE }}
          password: ${{ secrets.HARBOR_PASSWORD_LIVE }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY_URL_LIVE }}/discord/community-voice:${{ github.ref_name }}, ${{ secrets.HARBOR_REGISTRY_URL_LIVE }}/discord/community-voice:${{ github.run_id }}
